"""
Proper SQLite schema definitions for all 22 collections.
Uses SQLAlchemy Core table definitions.
"""
from sqlalchemy import (
    MetaData, Table, Column, Text, Integer, Float,
    Index, ForeignKey
)

metadata = MetaData()

users = Table('users', metadata,
    Column('id', Text, primary_key=True),
    Column('email', Text, nullable=False),
    Column('password', Text, nullable=False),
    Column('role', Text, nullable=False, default='student'),
    Column('is_active', Integer, default=1),
    Column('name', Text, default=''),
    Column('village_city_name', Text, default=''),
    Column('tehsil', Text, default=''),
    Column('district', Text, default=''),
    Column('state', Text, default=''),
    Column('phone', Text, default=''),
    Column('whatsapp', Text, default=''),
    Column('gender', Text, default=''),
    Column('semester', Text, default=''),
    Column('department', Text, default=''),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('college_id', Text, ForeignKey('colleges.id'), nullable=True),
    Column('university_logo_override', Text, default=''),
    Column('college_logo_override', Text, default=''),
    Column('degree_id', Text, ForeignKey('degrees.id'), nullable=True),
    Column('academic_department_id', Text, ForeignKey('departments.id'), nullable=True),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('roll_number', Text, default=''),
    Column('enrollment_number', Text, default=''),
    Column('industry_id', Text, ForeignKey('industries.id'), nullable=True),
    Column('supervisor_name', Text, default=''),
    Column('supervisor_contact', Text, default=''),
    Column('industry_profile_customized', Integer, default=0),
    Column('industry_village_city_name', Text, default=''),
    Column('industry_tehsil', Text, default=''),
    Column('industry_district', Text, default=''),
    Column('industry_state', Text, default=''),
    Column('industry_website', Text, default=''),
    Column('industry_gst_number', Text, default=''),
    Column('industry_details', Text, default=''),
    Column('industry_type', Text, default=''),
    Column('industry_sub_type', Text, default=''),
    Column('industry_key_activities', Text, default='[]'),
    Column('profile_completed', Integer, default=0),
    Column('email_verified', Integer, default=0),
    Column('email_verify_otp_hash', Text, nullable=True),
    Column('email_verify_otp_exp', Text, nullable=True),
    Column('email_verify_attempts', Integer, default=0),
    Column('reset_otp_hash', Text, nullable=True),
    Column('reset_otp_expires_at', Text, nullable=True),
    Column('reset_otp_attempt_count', Integer, default=0),
    Column('created_at', Text),
    Column('updated_at', Text),
)

degrees = Table('degrees', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('is_active', Integer, default=1),
    Column('approval_status', Text, default='approved'),
    Column('policy', Text, default='{}'),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

departments = Table('departments', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('degree_id', Text, ForeignKey('degrees.id'), nullable=True),
    Column('approval_status', Text, default='approved'),
    Column('rejection_reason', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

majors = Table('majors', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('degree_id', Text, ForeignKey('degrees.id'), nullable=True),
    Column('department_id', Text, ForeignKey('departments.id'), nullable=True),
    Column('report_language', Text, default='English'),
    Column('report_content_type', Text, default='Text'),
    Column('ai_prompt_context', Text, default=''),
    Column('report_policy', Text, default='{}'),
    Column('report_sections', Text, default='[]'),
    Column('employment_opportunities', Text, default='[]'),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

universities = Table('universities', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('village_city_name', Text, default=''),
    Column('tehsil', Text, default=''),
    Column('district', Text, default=''),
    Column('state', Text, default=''),
    Column('website', Text, default=''),
    Column('logo', Text, default=''),
    Column('approval_status', Text, default='approved'),
    Column('rejection_reason', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

colleges = Table('colleges', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('village_city_name', Text, default=''),
    Column('tehsil', Text, default=''),
    Column('district', Text, default=''),
    Column('state', Text, default=''),
    Column('website', Text, default=''),
    Column('logo', Text, default=''),
    Column('approval_status', Text, default='approved'),
    Column('rejection_reason', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('is_verified', Integer, default=0),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

industries = Table('industries', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('industry_type', Text, default=''),
    Column('industry_sub_type', Text, default=''),
    Column('village_city_name', Text, default=''),
    Column('tehsil', Text, default=''),
    Column('district', Text, default=''),
    Column('state', Text, default=''),
    Column('website', Text, default=''),
    Column('logo', Text, default=''),
    Column('gst_number', Text, default=''),
    Column('details', Text, default=''),
    Column('key_activities', Text, default='[]'),
    Column('approval_status', Text, default='approved'),
    Column('rejection_reason', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('is_verified', Integer, default=0),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

reports = Table('reports', metadata,
    Column('id', Text, primary_key=True),
    Column('user_id', Text, ForeignKey('users.id'), nullable=True),
    Column('project_title', Text, default=''),
    Column('internship_type', Text, default=''),
    Column('report_academic_year', Text, default=''),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('college_id', Text, ForeignKey('colleges.id'), nullable=True),
    Column('degree_id', Text, ForeignKey('degrees.id'), nullable=True),
    Column('department_id', Text, ForeignKey('departments.id'), nullable=True),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('industry_id', Text, ForeignKey('industries.id'), nullable=True),
    Column('status', Text, default='pending'),
    Column('is_paid', Integer, default=0),
    Column('generated_content', Text, default='{}'),
    Column('edited_content', Text, default='{}'),
    Column('generated_titles', Text, default='{}'),
    Column('section_images', Text, default='{}'),
    Column('university_snapshot', Text, default='{}'),
    Column('college_snapshot', Text, default='{}'),
    Column('industry_snapshot', Text, default='{}'),
    Column('work_keywords', Text, default='[]'),
    Column('selected_sections', Text, default='[]'),
    Column('report_config', Text, default='{}'),
    Column('callback_url', Text, default=''),
    Column('error_message', Text, default=''),
    Column('pdf_generated_at', Text, nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

work_keywords = Table('work_keywords', metadata,
    Column('id', Text, primary_key=True),
    Column('keyword', Text, nullable=False),
    Column('industry_type', Text, default=''),
    Column('job_profile', Text, default=''),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('sort_order', Integer, default=0),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

project_titles = Table('project_titles', metadata,
    Column('id', Text, primary_key=True),
    Column('title', Text, nullable=False),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('degree_id', Text, ForeignKey('degrees.id'), nullable=True),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

university_report_templates = Table('university_report_templates', metadata,
    Column('id', Text, primary_key=True),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('sections', Text, default='[]'),
    Column('is_active', Integer, default=1),
    Column('use_as_default', Integer, default=0),
    Column('description', Text, default=''),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

college_report_templates = Table('college_report_templates', metadata,
    Column('id', Text, primary_key=True),
    Column('college_id', Text, ForeignKey('colleges.id'), nullable=True),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('sections', Text, default='[]'),
    Column('use_university_default', Integer, default=1),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

major_report_templates = Table('major_report_templates', metadata,
    Column('id', Text, primary_key=True),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('college_id', Text, ForeignKey('colleges.id'), nullable=True),
    Column('university_id', Text, ForeignKey('universities.id'), nullable=True),
    Column('sections', Text, default='[]'),
    Column('use_level_above_default', Integer, default=1),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

report_content_types = Table('report_content_types', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('sort_order', Integer, default=0),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

audit_logs = Table('audit_logs', metadata,
    Column('id', Text, primary_key=True),
    Column('user_id', Text, ForeignKey('users.id'), nullable=True),
    Column('action', Text, default=''),
    Column('target_type', Text, default=''),
    Column('target_id', Text, default=''),
    Column('detail', Text, default='{}'),
    Column('created_at', Text),
)

video_guides = Table('video_guides', metadata,
    Column('id', Text, primary_key=True),
    Column('title', Text, nullable=False),
    Column('video_url', Text, default=''),
    Column('description', Text, default=''),
    Column('sort_order', Integer, default=0),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

resumes = Table('resumes', metadata,
    Column('id', Text, primary_key=True),
    Column('user_id', Text, ForeignKey('users.id'), nullable=True),
    Column('title', Text, default='Untitled Resume'),
    Column('full_name', Text, default=''),
    Column('address', Text, default=''),
    Column('phone', Text, default=''),
    Column('email', Text, default=''),
    Column('photo_url', Text, default=''),
    Column('linkedin_url', Text, default=''),
    Column('github_url', Text, default=''),
    Column('career_objective_raw', Text, default=''),
    Column('career_objective_enhanced', Text, default=''),
    Column('education', Text, default='[]'),
    Column('experience', Text, default='[]'),
    Column('skills', Text, default='[]'),
    Column('technical_skills', Text, default='[]'),
    Column('projects', Text, default='[]'),
    Column('volunteering', Text, default='[]'),
    Column('certifications', Text, default='[]'),
    Column('languages', Text, default='[]'),
    Column('coursework', Text, default='[]'),
    Column('personal_skills', Text, default='[]'),
    Column('status', Text, default='draft'),
    Column('error_message', Text, default=''),
    Column('download_count', Integer, default=0),
    Column('created_at', Text),
    Column('updated_at', Text),
)

career_objectives = Table('career_objectives', metadata,
    Column('id', Text, primary_key=True),
    Column('text', Text, nullable=False),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('approval_status', Text, default='approved'),
    Column('rejection_reason', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('created_by_id', Text, ForeignKey('users.id'), nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

resume_keywords = Table('resume_keywords', metadata,
    Column('id', Text, primary_key=True),
    Column('keyword', Text, nullable=False),
    Column('category', Text, nullable=False),
    Column('industry_type', Text, default=''),
    Column('major_id', Text, ForeignKey('majors.id'), nullable=True),
    Column('is_active', Integer, default=1),
    Column('sort_order', Integer, default=0),
    Column('created_at', Text),
    Column('updated_at', Text),
)

contact_submissions = Table('contact_submissions', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, default=''),
    Column('email', Text, default=''),
    Column('phone', Text, default=''),
    Column('subject', Text, default=''),
    Column('message', Text, default=''),
    Column('status', Text, default='new'),
    Column('created_at', Text),
)

assignment_sessions = Table('assignment_sessions', metadata,
    Column('id', Text, primary_key=True),
    Column('user_id', Text, ForeignKey('users.id'), nullable=True),
    Column('title', Text, default='Untitled Assignment'),
    Column('assignment_type', Text, nullable=False),
    Column('university_name', Text, default=''),
    Column('degree_name', Text, default=''),
    Column('major_name', Text, default=''),
    Column('context_inputs', Text, default='{}'),
    Column('document_sections', Text, default='[]'),
    Column('full_content_markdown', Text, default=''),
    Column('chat_history', Text, default='[]'),
    Column('status', Text, default='draft'),
    Column('error_message', Text, default=''),
    Column('word_count_current', Integer, default=0),
    Column('word_count_target', Integer, default=0),
    Column('generation_count', Integer, default=0),
    Column('api_tokens_consumed', Integer, default=0),
    Column('is_deleted', Integer, default=0),
    Column('created_at', Text),
    Column('updated_at', Text),
)

assignment_prompts = Table('assignment_prompts', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('assignment_type', Text, default='*'),
    Column('trigger_keywords', Text, default='[]'),
    Column('injected_instruction', Text, nullable=False),
    Column('sort_order', Integer, default=0),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

payments = Table('payments', metadata,
    Column('id', Text, primary_key=True),
    Column('user_id', Text, ForeignKey('users.id'), nullable=True),
    Column('report_id', Text, ForeignKey('reports.id'), nullable=True),
    Column('service_id', Text, ForeignKey('services.id'), nullable=True),
    Column('amount', Float, default=0),
    Column('currency', Text, default='INR'),
    Column('status', Text, default='pending'),
    Column('payment_method', Text, default=''),
    Column('transaction_id', Text, default=''),
    Column('gateway_data', Text, default='{}'),
    Column('created_at', Text),
    Column('updated_at', Text),
)

services = Table('services', metadata,
    Column('id', Text, primary_key=True),
    Column('name', Text, nullable=False),
    Column('type', Text, default=''),
    Column('price', Float, default=0),
    Column('gst_included', Integer, default=0),
    Column('gst_percent', Float, default=0),
    Column('free_limit', Integer, default=0),
    Column('description', Text, default=''),
    Column('is_active', Integer, default=1),
    Column('degree_pricing', Text, default='[]'),
    Column('created_at', Text),
    Column('updated_at', Text),
)

blog_posts = Table('blog_posts', metadata,
    Column('id', Text, primary_key=True),
    Column('title', Text, nullable=False),
    Column('slug', Text, nullable=False),
    Column('excerpt', Text, default=''),
    Column('content', Text, default=''),
    Column('cover_image', Text, default=''),
    Column('tags', Text, default='[]'),
    Column('author', Text, default='ReportGen Team'),
    Column('is_published', Integer, default=0),
    Column('published_at', Text, nullable=True),
    Column('created_at', Text),
    Column('updated_at', Text),
)

faq_items = Table('faq_items', metadata,
    Column('id', Text, primary_key=True),
    Column('question', Text, nullable=False),
    Column('answer', Text, nullable=False),
    Column('category', Text, default='General'),
    Column('sort_order', Integer, default=0),
    Column('is_active', Integer, default=1),
    Column('created_at', Text),
    Column('updated_at', Text),
)

INDEXES = [
    Index('idx_users_email', users.c.email, unique=True),
    Index('idx_users_role_active', users.c.role, users.c.is_active),
    Index('idx_degrees_name', degrees.c.name, unique=True),
    Index('idx_departments_degree', departments.c.degree_id),
    Index('idx_departments_status', departments.c.approval_status, departments.c.is_active),
    Index('idx_majors_degree', majors.c.degree_id),
    Index('idx_majors_active', majors.c.is_active),
    Index('idx_universities_status', universities.c.approval_status, universities.c.is_active),
    Index('idx_colleges_university', colleges.c.university_id),
    Index('idx_colleges_status', colleges.c.approval_status, colleges.c.is_active),
    Index('idx_industries_type', industries.c.industry_type),
    Index('idx_industries_status', industries.c.approval_status, industries.c.is_active),
    Index('idx_reports_user', reports.c.user_id),
    Index('idx_reports_status', reports.c.status),
    Index('idx_reports_created', reports.c.created_at),
    Index('idx_audit_user', audit_logs.c.user_id),
    Index('idx_audit_action', audit_logs.c.action),
    Index('idx_work_keywords_major', work_keywords.c.major_id),
    Index('idx_project_titles_major', project_titles.c.major_id),
    Index('idx_resumes_user', resumes.c.user_id),
    Index('idx_resumes_status', resumes.c.status),
    Index('idx_assignments_user', assignment_sessions.c.user_id),
    Index('idx_assignments_status', assignment_sessions.c.status),
    Index('idx_payments_user', payments.c.user_id),
    Index('idx_payments_status', payments.c.status),
    Index('idx_blog_slug', blog_posts.c.slug, unique=True),
    Index('idx_blog_published', blog_posts.c.is_published, blog_posts.c.published_at),
    Index('idx_faq_active', faq_items.c.is_active, faq_items.c.sort_order),
    Index('idx_resume_keywords_cat', resume_keywords.c.category, resume_keywords.c.is_active),
    Index('idx_career_obj_status', career_objectives.c.approval_status, career_objectives.c.is_active),
    Index('idx_urt_university', university_report_templates.c.university_id),
    Index('idx_crt_college', college_report_templates.c.college_id),
    Index('idx_mrt_major', major_report_templates.c.major_id),
]
